= Tritium Project
An open source RISC based balanced ternary computer research project

== This is a research project
This project is not fully intended to get a perfectly functional computer out to the market, but rather, it is intended to get the concept of ternary computing out to the public so more people will start researching ternary computing as an alternative to binary computing. 

== What does balanced ternary mean?
Normal computers process data in binary which means two states, a one and a zero. Ternary is similar except operating on three states. In balanced ternary, there is a negative (i), neutral (0), and positive (1) which means numbers are naturally signed thus simplifying the architecture and general logic. Ternary also has the best radix efficiency for any integer base of 1.0046 where binary is 1.0615 with base e, 1.0000 being the most efficient. A 'trit' is the ternary analogue of a bit which stores an i (-1), 0, or 1. 

== Has this been done before?
There are many projects similar to this but they either haven't gone very far, closed source and secretive, or dead. The main inspiration for this project is the Russian Setun computer, more specifically the Setun-70 which has an 18 trit word and 81 words of memory with a magnetic drum holding more memory. 

== Variants
6, 9, 27, 54, and maybe even 81 trit word variants will be made with a similar architecture. The 9 trit architecture being dubbed 'Tritium-6' will be made first as an experiment and prototype.

== Directory Structure
* docs - contains documentation on the project and lab results
* emulators - a non-functional and really broken attempt at making an emulator
* kicad - contains the kicad project files for each part and revision
* library - contains all of the kicad libraries such as the footprints, spice models, and symbols
* pcbs - contains plotted gerber files for each pcb and revision
* schematics - contains all of the schematic files as a pdf for each revision
* simulation - contains tests setup to simulate basic logic and other various circuitry test using ngspice

== Tritium-6
=== Design Goals
* Around or less than $250 in components
* Have the ability to communicate with binary components
* Use easily sourcable parts
* One clock cycle per instruction

== Tritium-9
=== Design Goals
* Around or less than $500 in components
* Have the ability to communicate with binary components
* Use easily sourcable parts

### Current Status
Ordered rev.3 gates and other components to start testing more complicated circuits such as arithmetic, memory, and multiplexing