#!/usr/bin/env sh

python -m kikit.ui panelize \
--layout 'grid; rows: 8; cols: 4; space: 2mm' \
--tabs 'fixed; width: 3mm; vcount: 2' \
--cuts 'mousebites; drill: 0.5mm; spacing: 1mm; offset: 0.2mm; prolong: 0.5mm' \
--framing 'frame; width: 5mm; hspace: 8.985mm; vspace: 2.446mm; mintotalheight: 100mm; mintotalwidth: 100mm' \
--tooling '3hole; hoffset: 2.5mm; voffset: 2.5mm; size: 1.5mm' \
--fiducials '3fid; hoffset: 5mm; voffset: 2.5mm; coppersize: 2mm; opening: 1mm;' \
--text 'simple; text: JLCJLCJLCJLC; anchor: mt; voffset: 2.5mm; hjustify: center; vjustify: center;' \
--post 'millradius: 1mm' \
nquadstate.kicad_pcb panel.kicad_pcb